title: "João Capinha's Page"
description: "Product Manager with 6+ years of experience looking for an inticing new challenge in Paris"
navigation:
  - name: "Home"
    url: "/"
  - name: "About Me"
    url: "/about"
  - name: "CV"
    url: "/cv"
  - name: "Blog"
    url: "/blog"
  - name: "Contacts"
    url: "/contacts"
